services:
  - type: web
    name: number-classifier-api
    env: node
    buildCommand: npm install && npm run build
    startCommand: node index.js
    envVars:
      - key: NODE_ENV
        value: production
